local_mss_realty/cms/urls.py
from django.urls import  path
from .views import HomeView

app_name = 'cms'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

local_mss_realty/local_mss_realty/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', include('registration.urls')),
    path('user/', include('user.urls')),
    path('', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local_mss_realty/registration/urls.py
from django.urls import path
from .views import RegistrationView, RegistrationPaymentView
# , LoginView, DashboardView, PropertyListingView, PropertyCommissionView, PropertyRegistrationListView, PropertyDetailsView, ProfileView

app_name = 'registration'

urlpatterns = [
    path('', RegistrationView.as_view(), name='registration'),
    path('payment/', RegistrationPaymentView.as_view(), name='registration-payment'),
    # path('login/', LoginView.as_view(), name='login'),
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # path('property-listing/', PropertyListingView.as_view(), name='property-listing'),
    # path('property-details/', PropertyDetailsView.as_view(), name='property-details'),
    # path('property-commission/', PropertyCommissionView.as_view(), name='property-commission'),
    # path('profile/', ProfileView.as_view(), name='profile'),
    # path('property-registration/', PropertyRegistrationListView.as_view(), name='property-registration-list'),
]

local_mss_realty/user/urls.py
from django.urls import path
from .views import LoginView, DashboardView, PropertyListingView, PropertyCommissionView, PropertyRegistrationListView, PropertyDetailsView, ProfileView, EmailView, Error404View, Error500View, AnnouncementView

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
     path('announcement/', AnnouncementView.as_view(), name='announcement'),
    path('property-listing/', PropertyListingView.as_view(), name='property-listing'),
    path('property-details/', PropertyDetailsView.as_view(), name='property-details'),
    path('property-commission/', PropertyCommissionView.as_view(), name='property-commission'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('property-registration/', PropertyRegistrationListView.as_view(), name='property-registration-list'),
    path('email/', EmailView.as_view(), name='email'),
    path('error404/', Error404View.as_view(), name='error404'),
    path('error500/', Error500View.as_view(), name='error500'),
]

local_mss_realty/cms/models.py
from django.db import models

# Create your models here.

local_mss_realty/user/models.py
from django.db import models

# Create your models here.

local_mss_realty/cms/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = 'cms/home.html'

local_mss_realty/user/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class LoginView(TemplateView):
    template_name = "user/login.html"

class DashboardView(TemplateView):
    template_name = "user/dashboard.html"

class PropertyListingView(TemplateView):
    template_name = "user/property-listing.html"

class PropertyCommissionView(TemplateView):
    template_name = "user/property-commission.html"

class PropertyRegistrationListView(TemplateView):
    template_name = "user/property-registration-list.html"

class PropertyDetailsView(TemplateView):
    template_name = "user/property-details.html"

class AnnouncementView(TemplateView):
    template_name = "user/announcement.html"

class ProfileView(TemplateView):
    template_name = "user/profile.html"

class EmailView(TemplateView):
    template_name = "email/email.html"

class Error404View(TemplateView):
    template_name = 'error/error404.html'

class Error500View(TemplateView):
    template_name = 'error/error500.html'

local_mss_realty/templates/cms-base.html
{% load static sass_tags %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="MSS Mall">
    <meta name="author" content="MSS">
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'imgs/brand/apple-touch-icon.png' %}?v=1">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'imgs/brand/favicon-32x32.png' %}?v=1">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'imgs/brand/favicon-16x16.png' %}?v=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <link rel="stylesheet" href="{% static 'node_modules/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
    <link href="{% static 'node_modules/select2/dist/css/select2.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl-carousel/owl.theme.default.min.css' %}">
    <link href="{% sass_src 'scss/argon.scss' %}" rel="stylesheet" type="text/css" />
    <title>{% block title %}{% endblock title %} | AJ Realty</title>
    {% block page_css %}
    {% endblock page_css %}
</head>
<body data-spy="scroll" data-target="#cms-navbar" data-offset="100">
    {% block navbar %}
    <nav id="cms-navbar" class="navbar navbar-expand-lg cms-navbar navbar-light">
        <a class="navbar-brand" href="{% url 'cms:home' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-lg-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link sliding-link" href="#home">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link sliding-link" href="#about-us">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link sliding-link" href="#services">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link sliding-link" href="#contact">Contact</a>
                </li>
                <li class="nav-item ml-lg-3">
                    <a class="nav-link btn btn-primary text-white" href="{% url 'registration:registration' %}"">Become a Property Planner</a>
                </li>
            </ul>
        </div>
      </nav>
      {% endblock navbar %}

      {% block content %}
      {% endblock content %}

      {% block footer %}
      {% include "partials/footer.html" %}
      {% endblock footer %}


    <script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'node_modules/js-cookie/js.cookie.js' %}"></script>
    <script src="{% static 'node_modules/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'node_modules/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
    <script src="{% static 'node_modules/select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'js/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/argon.js' %}"></script>
    {% block page_js %}
    {% endblock page_js %}
</body>
</html>

local_mss_realty/templates/partials/dashboard-navbar.html
{% load static %}

<nav class="navbar dashboard-navbar navbar-expand-lg navbar-light">
    <a href="{% url 'user:dashboard' %}" class="navbar-brand navbar-logo" href="#"><img src="{% static 'img/logo/aj-logo.png' %}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto align-items-lg-center">
        <li class="nav-item mx-4">
            <a class="nav-link" href="{% url 'user:property-listing' %}">Products</a>
        </li>
        <li class="nav-item mx-4">
            <a class="nav-link" href="{% url 'user:announcement' %}">Announcement</a>
        </li>
        <li class="nav-item mx-4">
            <a class="nav-link" href="{% url 'user:property-commission' %}">Commissions</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link nav-dropdown-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                    <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{% static 'img/theme/team-1.jpg' %}">
                    </span>
                    <div class="media-body ml-2 d-none d-lg-block">
                        <span class="mb-0 text-sm  font-weight-bold">John Snow</span>
                    </div>
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <i class="ni ni-single-02"></i>
                    <span>My Profile</span>
                </a>
                <a href="#" class="dropdown-item">
                    <i class="ni ni-settings-gear-65"></i>
                    <span>Update Password</span>
                </a>
                <a href="#" class="dropdown-item">
                    <i class="ni ni-user-run"></i>
                    <span>Logout</span>
                </a>
            </div>
        </li>
      </ul>
    </div>
  </nav>

local_mss_realty/templates/partials/sidebar.html
{% load static sass_tags %}

<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header d-flex align-items-center">
      <a class="navbar-brand" href="{% url 'user:dashboard' %}">
        <img src="{% static 'img/logo/logo.png' %}" class="navbar-brand-img" style="width: 115px;height: auto;max-width: unset;max-height: unset;">
      </a>
      <div class="ml-auto">
        <!-- Sidenav toggler -->
        <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
          <div class="sidenav-toggler-inner">
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:dashboard' %}">
					<i class="fas fa-chart-bar"></i>
					<span class="nav-link-text">Dashboard</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:property-listing' %}">
					<i class="fas fa-building"></i>
					<span class="nav-link-text">Property Listing</span>
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user:property-commission' %}">
					<i class="fas fa-coins"></i>
					<span class="nav-link-text">Commissions</span>
				</a>
			</li>	
			<li class="nav-item">
                <a class="nav-link" href="{% url 'user:property-registration-list' %}">
					<i class="fas fa-folder"></i>
					<span class="nav-link-text">My Registration</span>
				</a>
			</li>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'user:profile' %}">
					<i class="fas fa-user"></i>
					<span class="nav-link-text">My Profile</span>
				</a>
			</li>
        </ul>
      </div>
    </div>
  </div>
</nav>

local_mss_realty/templates/user/dashboard.html
{% extends 'dashboard-base.html' %}
{% load static sass_tags %}

{% block sidebar %}
{% endblock sidebar %}

{% block portal_navbar %}
{% endblock portal_navbar %}

{% block content %}
<div class="dashboard-section">
    <div class="container">
        <h2 class="mb-4 ml-3 ml-md-0">AJ Products</h2>
        <div class="row dashboard-row">
            <div class="col-md-6 col-12 dashboard-product-col realty-product-col">
                <h3>AJ Realty</h3>
                <div class="dashboard-product-links">
                    <a class="mr-5" href="{% url 'cms:home' %}">Visit Site</a>
                    <a href="{% url 'user:property-listing' %}">Enter Portal</a>
                </div>
            </div>
            <div class="col-md-6 col-12 dashboard-product-col reliance-product-col">
                <h3>AJ Reliance</h3>
                <div class="dashboard-product-links">
                    <a class="mr-5" href="{% url 'cms:home' %}">Visit Site</a>
                    <a href="{% url 'user:property-listing' %}">Enter Portal</a>
                </div>
            </div>
            <div class="col-md-6 col-12 dashboard-product-col realty-product-col">
                <h3>AJ Realty</h3>
                <div class="dashboard-product-links">
                    <a class="mr-5" href="{% url 'cms:home' %}">Visit Site</a>
                    <a href="{% url 'user:property-listing' %}">Enter Portal</a>
                </div>
            </div>
            <div class="col-md-6 col-12 dashboard-product-col realty-product-col">
                <h3>AJ Realty</h3>
                <div class="dashboard-product-links">
                    <a class="mr-5" href="{% url 'cms:home' %}">Visit Site</a>
                    <a href="{% url 'user:property-listing' %}">Enter Portal</a>
                </div>
            </div>
        </div>

        <div class="row product-announcement-row">
            <div class="col-md-6 col-12 product-annoucement-col">
                <h2>Annoucement</h2>
                <div class="body">
                    <div class="mb-3 text-right">
                        <a href="{% url 'user:announcement' %}">See All</a>
                    </div>
                    <div class="row mb-3 mb-lg-0">
                        <div class="col-lg-4 col-md-8 col-12 mb-2 mb-lg-3">
                            <div class="date">
                                <p class="mb-0">29 Sep 2020</p>
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-12 col-12">
                            <div class="info">
                                <p class="mb-0">Lorem ipsum dolor sit amet.</p>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3 mb-lg-0">
                        <div class="col-lg-4 col-md-8 col-12 mb-2 mb-lg-3">
                            <div class="date">
                                <p class="mb-0">29 Sep 2020</p>
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-12 col-12">
                            <div class="info">
                                <p class="mb-0">Lorem ipsum dolor sit amet.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-12 product-commissions-col">
                <h2>Commissions</h2>
                <div class="body">
                    <div class="mb-3 text-right">
                        <a href="{% url 'user:property-commission' %}">See All</a>
                    </div>
                    <div class="row mb-3 mb-lg-0">
                        <div class="col-md-4 col-12 mb-3">
                            <div class="date">
                                <p class="mb-0">29 Sep 2020</p>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="amount">
                                <p class="mb-0">RM1222</p>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="status">
                                <p class="mb-0 text-right successful">Successful</p>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3 mb-lg-0">
                        <div class="col-md-4 col-12 mb-3">
                            <div class="date">
                                <p class="mb-0">29 Sep 2020</p>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="amount">
                                <p class="mb-0">RM1222</p>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="status">
                                <p class="mb-0 text-right pending">Pending</p>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-3 mb-lg-0">
                        <div class="col-md-4 col-12 mb-3">
                            <div class="date">
                                <p class="mb-0">29 Sep 2020</p>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="amount">
                                <p class="mb-0">RM1222</p>
                            </div>
                        </div>
                        <div class="col-md-4 col-6">
                            <div class="status">
                                <p class="mb-0 text-right unsuccessful">Unsuccessful</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>  
</div>
{% endblock content %}

local_mss_realty/templates/user/login.html
{% extends 'dashboard-base.html' %}
{% load static sass_tags %}

{% block page_css %}
    <style>
        .navbar-nav {
            display: none;
        }

        .navbar-toggler-icon {
            display: none;
        }
    </style>
{% endblock page_css %}

{% block sidebar %}
{% endblock sidebar %}

{% block portal_navbar %}
{% endblock portal_navbar %}

{% block content %}
<div class="registration-section">
    <div class="container-fluid">
        <div class="registration-body login-body">
            <form class="login-form">
                <h2 class="mb-4">Advertiser Programme</h2>
                <div class="form-row mb-3">
                    <div class="col-12">
                        <input type="text" class="form-control" placeholder="Username">
                    </div>
                </div>
                <div class="form-row mb-3">
                    <div class="col-12">
                        <input type="password" class="form-control" placeholder="Password">
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <div>
                        <input type="checkbox">
                        <label>Remember Me</label>
                    </div>
                    <a href="#" class="d-flex align-self-center">Forgot your password?</a>
                </div>
                <div class="btn-div text-center">
                    <button class="btn btn-primary">Log In</button>
                </div>
            </form>
        </div>
    </div>  
</div>
{% endblock content %}

local_mss_realty/templates/user/property-details.html
{% extends 'dashboard-base.html' %}
{% load static sass_tags %}

{% block navbar %}
{% endblock navbar %}

{% block content %}
<div class="programme-section">
    <div class="commission-header pl-5">
        <div class="container">
            <a class="text-white" href="{% url 'user:property-listing' %}"><img class="mr-2" style="width: 14px;" src="{% static 'img/icons/back-white.png' %}" alt=""> Back</a>
        </div>
    </div>
    <div class="container">
        <div class="programme-body property-programme-body px-4">
            <div class="programme-content property-programme-content">
                <div class="property-content-body">
                    <div class="property-details-name">
                        <h2 class="mb-0">Property Name Line 1</h2>
                        <h2 class="mb-0">Property Name Line 2</h2>
                    </div>
                    <div class="owl-carousel property-carousel owl-theme" data-slider-id="1">
                        <div class="featured-owl-img"> 
                            <img src="{% static 'img/theme/team-1.jpg' %}" alt="">
                        </div>
                        <div class="featured-owl-img">
                            <img src="{% static 'img/theme/team-2.jpg' %}" alt="">
                        </div>
                        <div class="featured-owl-img">
                            <img src="{% static 'img/theme/team-3.jpg' %}" alt="">
                        </div>
                        <div class="featured-owl-img">
                            <img src="{% static 'img/theme/team-4.jpg' %}" alt="">
                        </div>
                        <div class="featured-owl-img"> 
                            <img src="{% static 'img/theme/team-1.jpg' %}" alt="">
                        </div>
                        <div class="featured-owl-img">
                            <img src="{% static 'img/theme/team-2.jpg' %}" alt="">
                        </div>
                        <div class="featured-owl-img">
                            <img src="{% static 'img/theme/team-3.jpg' %}" alt="">
                        </div>
                        <div class="featured-owl-img">
                            <img src="{% static 'img/theme/team-4.jpg' %}" alt="">
                        </div>
                    </div>
                    <div class="owl-thumbs" data-slider-id="1">
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-1.jpg' %}" alt=""></button>
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-2.jpg' %}" alt=""></button>
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-3.jpg' %}" alt=""></button>
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-4.jpg' %}" alt=""></button>
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-1.jpg' %}" alt=""></button>
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-2.jpg' %}" alt=""></button>
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-3.jpg' %}" alt=""></button>
                        <button class="owl-thumb-item"><img src="{% static 'img/theme/team-4.jpg' %}" alt=""></button>
                    </div>
                    <div class="property-details-body">
                        <h3><i class="fas fa-tag mr-2 mb-3"></i>RM 2,000,000</h3>
                        <div class="details mb-5">
                            <h4 class="mb-3">Property Details</h4>
                            <div class="category-type mb-3">
                                <p class="mb-0 type text-grey avenir-roman">Category Type</p>
                                <p class="mb-0">Houses</p>
                            </div>
                            <div class="category-type mb-3">
                                <p class="mb-0 type text-grey avenir-roman">Property Type</p>
                                <p class="mb-0">Double Storey</p>
                            </div>
                            <div class="category-type mb-3">
                                <p class="mb-0 type text-grey">Title Type</p>
                                <p class="mb-0">Freehold</p>
                            </div>
                            <div class="category-type mb-3">
                                <p class="mb-0 type text-grey avenir-roman">Size</p>
                                <p class="mb-0">2,22 sqft</p>
                            </div>
                            <div class="category-type mb-3">
                                <p class="mb-0 type text-grey avenir-roman">Other Info</p>
                                <p class="mb-0">Non Bumi lot</p>
                            </div>
                        </div>
                        <div class="description mb-5">
                            <p class="mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet optio delectus libero enim corrupti praesentium ipsam earum? Quae, laboriosam ducimus?</p>
                            <p class="mb-0">Property video: <a href="#">https://blabla</a></p>
                        </div>
                        <div class="resources mb-5">
                            <div class="resources-type mb-3">
                                <p class="mb-0 type text-grey avenir-roman">Brochure</p>
                                <a href="#">Download</a>
                            </div>
                            <div class="resources-type mb-3">
                                <p class="mb-0 type text-grey avenir-roman">Floor Plan</p>
                                <a href="#">Download</a>
                            </div>
                            <div class="resources-type mb-3">
                                <p class="mb-0 type text-grey avenir-roman">Booking Form</p>
                                <a href="#">Download</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  
</div>
{% endblock content %}

{% block page_js %}
<script>
    $(document).ready(function(){
        $(".property-carousel").owlCarousel({
            loop:true,
            margin:20,
            responsiveClass:true,
            thumbs: true,
            thumbsPrerendered: true,
            navText : ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"],
            responsive:{
                0:{
                    items:1,
                },
                600:{
                    items:1,
                },
                1000:{
                    items:1,
                }
            }
        });
    });
    </script>
{% endblock page_js %}

local_mss_realty/templates/user/property-listing.html
{% extends 'dashboard-base.html' %}
{% load static sass_tags %}

{% block navbar %}
{% endblock navbar %}

{% block content %}
<div class="programme-section">
    <div class="commission-header pl-5">
        <div class="container">
            <h2>Property Listing</h2>
        </div>
    </div>
    <div class="container">
        <div class="programme-body property-programme-body px-4">
            <div class="programme-content">
                <div class="programme-list">
                    <div class="row programme-list-row no-gutters">
                        <div class="col-md-5 col-12 programme-list-img-col">
                            <img src="{% static 'img/theme/team-1.jpg' %}" alt="">
                        </div>
                        <div class="col-md-7 col-12 programme-info-col">
                            <div class="programme-property-info">
                                <div class="property-name">
                                    <h3 class="mb-0">Property Name Line 1</h3>
                                    <h3 class="mb-0">Property Name Line 2</h3>
                                </div>
                                <div class="property-type">
                                    <small>House</small>
                                </div>
                                <div class="property-price">
                                    <h4 class="mb-2 mb-md-0 mt-2">RM4,000,000</h4>
                                </div>
                                <div class="property-size mb-3 mb-md-2">
                                    <small>2,722 sqft</small>
                                </div>
                                <div class="btn-div">
                                    <button class="btn btn-primary mb-3 mb-md-1">Download Resources</button>
                                    <a class="btn btn-outline-primary mb-md-1" href="{% url 'user:property-details' %}">View Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="programme-list">
                    <div class="row programme-list-row no-gutters">
                        <div class="col-md-5 col-12 programme-list-img-col">
                            <img src="{% static 'img/theme/team-1.jpg' %}" alt="">
                        </div>
                        <div class="col-md-7 col-12 programme-info-col">
                            <div class="programme-property-info">
                                <div class="property-name">
                                    <h3 class="mb-0">Property Name Line 1</h3>
                                    <h3 class="mb-0">Property Name Line 2</h3>
                                </div>
                                <div class="property-type">
                                    <small>House</small>
                                </div>
                                <div class="property-price">
                                    <h4 class="mb-2 mb-md-0 mt-2">RM4,000,000</h4>
                                </div>
                                <div class="property-size mb-3 mb-md-2">
                                    <small>2,722 sqft</small>
                                </div>
                                <div class="btn-div">
                                    <button class="btn btn-primary mb-3 mb-md-1">Download Resources</button>
                                    <a class="btn btn-outline-primary mb-md-1" href="{% url 'user:property-details' %}">View Details</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav aria-label="Page navigation example text-right">
            <ul class="pagination px-5">
                <li class="page-item mx-1"><a class="page-link" href="#"><</a></li>
                <li class="page-item mx-1 active"><a class="page-link" href="#">1</a></li>
                <li class="page-item mx-1"><a class="page-link" href="#">2</a></li>
                <li class="page-item mx-1"><a class="page-link" href="#">3</a></li>
                <li class="page-item mx-1"><a class="page-link" href="#">></a></li>
            </ul>
        </nav>
    </div>  
</div>
{% endblock content %}